### ISSUE TITLE
F001 Events anlegen

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#1]
**Die Plattform soll es Benutzern ermöglichen, Events zu erstellen, indem sie folgende Informationen angeben: Name des Events, Datum, Uhrzeit, Veranstaltungsort. **

Die Möglichkeit, Events auf der Plattform zu erstellen, ist eine Kernfunktion, die es Veranstaltern ermöglicht Events zu planen und zu organisieren. Diese Funktion kann zu einer steigenden Nutzerzahl beitragen.

- [ ] Veranstalter sollten in der Lage sein, ein neues Event anzulegen, indem sie ein Formular ausfüllen, in dem sie alle relevanten Informationen angeben.

**Comment by dangllucas** [comment]
BE Funktion implementiert
