### ISSUE TITLE
Missverständlicher Routenname

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#112]
![image](https://github.com/party-time-2/party-time/assets/33830803/05ededa3-0655-4785-94ed-fd483f5489d6)

![image](https://github.com/party-time-2/party-time/assets/33830803/27f53d8d-7f56-40ea-b1b5-c801c8488fa8)

Passt irgendwie nicht zusammen

![image](https://github.com/party-time-2/party-time/assets/33830803/b392a4b0-ac39-46b9-b99d-99e77174ce7b)

/api/events macht mehr Sinn

**Comment by E3FxGaming** [comment]
Wurde in der überarbeiteten API berücksichtigt.
