### ISSUE TITLE
addressLineAddition in Frontend nicht nullable

### ISSUE THREAD

**Issue by E3FxGaming** [party-time-2/party-time#113]
Das Feld `addressLineAddition` des `AddressDTO` ist im Backend nullable

https://github.com/party-time-2/party-time/blob/bed34424c4c4183c7ac8671a4d8c1c71f46a9f4b/apps/party-time-backend-kotlin/src/main/kotlin/com/partytime/api/dto/address/AddressDTO.kt#L9

im Frontend hingegen nicht nullable

https://github.com/party-time-2/party-time/blob/bed34424c4c4183c7ac8671a4d8c1c71f46a9f4b/libs/models/src/lib/api/event.model.ts#L25

Aktuell sendet das Backend im Falle eines Null-Wertes einen leeren String, es wäre aber besser wenn tatsächlich ein `null` Wert übermittelt werden kann und das Frontend entsprechend darauf reagiert (in dem es die `addressLineAddition` nur anzeigt, wenn diese nicht `null` ist).

**Comment by JulianTurner** [comment]
implementiert
