### ISSUE TITLE
Abgabe Praxisprojekt III

### ISSUE THREAD

**Issue by E3FxGaming** [party-time-2/party-time#123]
Gemeinsam:

- [x] Besprechen, was wir mit dem E-MailAPI Key machen
- [x] Test-Coverage Ergebnisse für Abgabe archivieren

Kay

- [x] Szenario Test "Gast Einladen"
- [x] README.md Abschnitt ausfüllen
- [x] Präsentation Coverage Bild ersetzen

**Comment by JulianTurner** [comment]
Der Email API Key spielt doch keine Rolle. Würde ich gnadenlos ignorieren
