### ISSUE TITLE
F014 Konto verifizieren

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#14]
**Die Plattform muss in der Lage sein, Benutzerkonten zu verifizieren, um sicherzustellen, dass die angegebenen Informationen korrekt sind und dass die Benutzer echt sind.**

Durch die Verifizierung von Benutzerkonten kann das Vertrauen der Benutzer in die Plattform gestärkt werden und es kann dazu beitragen, dass betrügerische Aktivitäten reduziert werden.

- [ ] Benutzer müssen bei der Registrierung Name und E-Mail-Adresse angeben.

**Comment by E3FxGaming** [comment]
JSON Web Token für Koto-Verifizierung muss "E-Mail-Verifizierung" Flag in Payload enthalten (sich von normalen JWT für Sessions unterscheiden), da sonst Session JWT für E-Mail-Verifizerung missbraucht werden können.
