### ISSUE TITLE
F018 Wegbeschreibung zum Event

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#18]
**Die Teilnehmer eines Events benötigen eine detaillierte Wegbeschreibung, um das Event ohne Schwierigkeiten zu finden.**

Wenn Teilnehmer eines Events das Event aufgrund einer fehlender Wegbeschreibung nicht finden, kann dies zu Verspätungen und Verzögerungen beim Event führen.

- [x] Die Wegbeschreibung sollte klar, präzise und leicht verständlich sein. 

- [x] Die Wegbeschreibung sollte auch rechtzeitig vor dem Event verfügbar sein, damit die Gäste ausreichend Zeit haben, sich vorzubereiten.

**Comment by dangllucas** [comment]
https://jsfiddle.net/v0sjrx91/2/
