### ISSUE TITLE
F019 Kalendereintrag exportieren

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#19]
**Die Nutzer sollen die Möglichkeit haben, Kalendereinträge aus der Event-Plattform in andere Kalenderanwendungen zu exportieren.**

Nutzer können den Kalendereintrag in anderen Anwendungen wie z.B. Outlook oder Google Kalender importieren und den Termin automatisch in ihrem eigenen Kalender verfügbar machen.

Wird per Mail gesendet.

- [x] Der Nutzer kann den Kalendereintrag aus der Event-Plattform exportieren.
- [x] Der exportierte Kalendereintrag enthält alle relevanten Informationen wie z.B. Titel, Datum, Uhrzeit und Ort des Events.
- [x] Der exportierte Kalendereintrag ist in einem gängigen Dateiformat wie .ics verfügbar.
- [x] Der exportierte Kalendereintrag kann in anderen Kalenderanwendungen importiert werden.

**Comment by dangllucas** [comment]
TODO: Validierung des ICS
