### ISSUE TITLE
Passwortrichtlinie im Backend implementieren

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#35]
- [ ] Die Api darf nur Passwörter nach der Richtlinie in den Design Entscheidungen akzeptieren

**Comment by dangllucas** [comment]
- Mindestens 8 Zeichen lang sein
- Maximal 30 Zeichen lang sein
- 4 Zeichenarten verwenden (je min. 1 Großbuchstaben, Kleinbuchstaben, Ziffer und Sonderzeichen)
- Die 1 benötigte Ziffer und das 1 benötigte Sonderzeichen dürfen nicht am Anfang oder Ende des Passworts stehen. Auch eine Folge von Sonderzeichen und Ziffern am Anfang und Ende erfüllen die Regel nicht.
- Als Sonderzeichen anerkannt werden: ,!"§$%&/()=?{}[]\ und Leerzeichen
