### ISSUE TITLE
Test Datenbank sollte bekannte Nutzer enthalten

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#37]
- [ ] 3x Verfizierter Nutzer ist angelegt
- [ ] Nicht verifizierter Nutzer ist angelegt

**Comment by dangllucas** [comment]
Sind jetzt jeweils 4 :D
Aber passt ja ;)

Jeweils Mails:
verified_<1-4>@partytime.de
not_verified_<1-4>@partytime.de
PW: Hallo123!party
