### ISSUE TITLE
Verifizierungs E-Mail überarbeiten

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#51]
- [x] Die E-Mail muss an das Design der Webseite angelegnt werden
- [x] Die Links müssen auf die entsprechende Stelle im Frontend leiten

**Comment by dangllucas** [comment]
@JulianTurner Kannst du da vielleicht ein simples html template bauen?

**Comment by JulianTurner** [comment]
Ja hatte ich vor, ist aber keine Prio im Moment
