### ISSUE TITLE
API erweitern

### ISSUE THREAD

**Issue by JulianTurner** [party-time-2/party-time#86]
Als Teilnehmer eines Events kann ich mit der EventId die Adresse zum Event bekommen.

**Comment by dangllucas** [comment]
@JulianTurner Das geht bereits..

Wenn nicht, dann hat das Event vl keine Adresse?

**Comment by dangllucas** [comment]
![image](https://github.com/party-time-2/party-time/assets/27855488/a0a5d2bf-2ce1-4d82-a8d7-ece118dd8180)
